# Generated by Django 3.2.7 on 2021-09-08 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_resource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=200)),
                ('contactEmail', models.EmailField(blank=True, max_length=254)),
                ('contactNumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='JournalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalName', models.CharField(max_length=200)),
                ('journalUrl', models.URLField()),
                ('lastAccessed', models.DateTimeField()),
                ('tagIds', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TagsResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=200)),
                ('tagUrl', models.URLField()),
                ('imageUrl', models.URLField(blank=True)),
            ],
        ),
    ]
