# Generated by Django 3.2.7 on 2021-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_contactsresource_journalresource_tagsresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalresource',
            name='tagIds',
            field=models.JSONField(blank=True),
        ),
    ]
