# Generated by Django 3.2.7 on 2021-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journalresource_tagids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalresource',
            name='tagIds',
        ),
        migrations.AddField(
            model_name='journalresource',
            name='contactNames',
            field=models.ManyToManyField(to='journal.ContactsResource'),
        ),
        migrations.AddField(
            model_name='journalresource',
            name='tagNames',
            field=models.ManyToManyField(to='journal.TagsResource'),
        ),
    ]
