# Generated by Django 3.2.7 on 2021-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20210909_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsresource',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
