# Generated by Django 3.2.7 on 2021-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_tagsresource_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalresource',
            name='lastAccessed',
            field=models.DateTimeField(null=True),
        ),
    ]
