# Generated by Django 3.2.7 on 2021-09-10 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journalresource_lastaccessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalresource',
            name='lastAccessed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
